version: '3'

volumes:
  local_postgres_data: {}

services:
  db:
    image: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
